//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;AACHEN HBF&quot;, &quot;Aachen Schanz&quot;, &quot;AACHEN SUD (GR.)&quot;, &quot;AACHEN SUED&quot;, &quot;Aachen Sued(gr)&quot;, &quot;Aachen West&quot;, &quot;Aachen-Rothe Erde&quot;, &quot;Aadorf&quot;, &quot;Aalbaek(vendsyssel)&quot;, &quot;AALBORG&quot;, &quot;Aalborg Vestby&quot;, &quot;AALEN&quot;, &quot;Aalholm&quot;, &quot;AALSGAARDE&quot;, &quot;Aalst&quot;, &quot;Aalst Kerrebroek&quot;, &quot;AALST ZONE&quot;, &quot;Aalten&quot;, &quot;Aalter&quot;, &quot;AAMARKEN&quot;, &quot;AARAU&quot;, &quot;Aarberg&quot;, &quot;Aarburg-Oftringen&quot;, &quot;AARHUS H&quot;, &quot;Aarhus Havn&quot;, &quot;Aarschot&quot;, &quot;Aarsele&quot;, &quot;Aarslev&quot;, &quot;Aarup&quot;, &quot;Aarwangen&quot;, &quot;Aarwangen Schloss&quot;, &quot;Aathal&quot;, &quot;Abakan&quot;, &quot;Abancourt&quot;, &quot;Abano&quot;, &quot;Abbadia Lariana&quot;, &quot;Abbadia S.Sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
    }
}
